const lessons = [
  {
    title: "Lesson 1: Intro to the DAW",
    steps: [
      { title: "Welcome!", 
        text: "Let's get started on your first lesson.", 
        position:{ top: 500, left: 900},
        hasArrow: false },
      {title: "DAW", 
        text: "DAW stands for Digital Audio Workstation. It is a software where you can record/edit tracks and more.", 
        position:{ top: 500, left: 900},
        hasArrow: false },
      { title: "Add a Track", 
        text: "Click the 'Add Track' button to create a new track. Click on your new track so it's outlined in blue.", 
        position:{ top: 425, left: 740},
        hasArrow: true},
      { title: "Record", 
        text: "Now click the 'Record' button to begin recording. Press 'Stop Recording' to stop the recording.", 
        position:{ top: 425, left: 850},
        hasArrow: true},
      { title: "Play", 
        text: "Press 'Play' (or the spacebar) to listen to your recording. After listening, press 'Pause' to stop.", 
        position:{ top: 425, left: 640},
        hasArrow: true},
      {title: "Playhead", 
        text: "The playhead is the red vertical line that shows your current position in the track. To set the playhead back to the beginning of the track, press 'Reset Playhead'.", 
        position:{ top: 475, left: 1125},
        hasArrow: true},
      {title: "Playhead", 
        text: "You can also use the slider to adjust the playhead to where you want it.", 
        position:{ top: 475, left: 200},
        hasArrow: true},
      {title: "Volume", 
        text: "Adjust the slider to change the volume of your track.", 
        position:{ top: 540, left: 225},
        hasArrow: true},
      {title: "Multiple tracks", 
        text: "Now let's add a new track. Click on the track and record.", 
        position:{ top: 415, left: 740},
        hasArrow: true},
      {title: "Mute Button", 
        text: "Press the 'mute' button to mute that track. Reset the playhead and press 'play'. Press play and notice how only the unmuted track has audio.", 
        position:{ top: 700, left: 200},
        hasArrow: true},
      {title: "Delete Button", 
        text: "Now select a track and click 'delete' to remove that track.", 
        position:{ top: 415, left: 970},
        hasArrow: true},
    ],
  },
  {
    title: "Controls",
    steps: [
      { title: "Compressor", 
        text: "Write lesson here.", 
        position:{ top: 500, left: 900},
        hasArrow: true},
      { title: "EQ", 
        text: "Write lesson here.", 
        position:{ top: 500, left: 900},
        hasArrow: true},
      { title: "Reverb", 
        text: "Write lesson here.", 
        position:{ top: 500, left: 900},
        hasArrow: true},
    ],
  },
];

export default lessons;
